In [1]:
#Dosyalar ve istisnalar

In [2]:
f = open("testAI7.txt", "w")
print(f)

<_io.TextIOWrapper name='testAI7.txt' mode='w' encoding='cp1254'>


In [3]:
f.write("Now is the time")
f.write(" to close the file")
f.close()

In [4]:
f = open("testAI7.txt", "r")
text = f.read()
print(text)

Now is the time to close the file


In [5]:
f = open("testAI7.txt", "r")
print(f.read(5))

Now i


In [6]:
print(f.read(1000006))

s the time to close the file


In [7]:
fo = open("fooAI7.txt", "w")
fo.write("Python is a great language.\n Yeah its great!!\n")
fo.close()

In [8]:
fo = open("fooAI7.txt", "r+")
mystr1 = fo.read(17)
print("Our string is :", mystr1)

Our string is : Python is a great


In [9]:
position = fo.tell()
print("Current file position :", position)

Current file position : 17


In [10]:
position = fo.seek(0, 0)
mystr1 = fo.read(17)
print("Again our string is :", mystr1)

Again our string is : Python is a great


In [11]:
#try, except, else, finally

In [12]:
try:
    fh = open("testfileAI7", "r")
    fh.write("This is my test file for exception handling")
    
except IOError:
    print("Error : cannot find file or read data")
    
else:
    print("Written content in the file successfully")

Error : cannot find file or read data


In [13]:
try:
    fh = open("testfileAI7", "w")
    fh.write("This is my test file for exception handling")

finally:
    print("Written content in the file successfully")

Written content in the file successfully


In [14]:
dict = {'Name': 'Azra', 'Age': 2, 'Class': 'First'}
print(dict['Name'])
print(dict['Age'])

Azra
2


In [15]:
dict = {'Name': 'Azra', 'Age': 2, 'Class': 'First'}
dict['Age'] = 8
dict['School'] = 'Primary School'

In [16]:
print(dict['Age'])
print(dict['School'])

8
Primary School


In [17]:
dict = {'Name': 'Azra', 'Age': 2, 'Name': 'Ayşe'}
print(dict['Name'])

Ayşe


In [18]:
dict = {'Name': 'Azra', 'Age': 2, 'Class': 'First'}
del dict['Name']

In [19]:
dict.clear()

In [20]:
del dict

In [21]:
print(dict['Age'])
print(dict['Class'])

TypeError: 'type' object is not subscriptable

In [22]:
phonebook = {'Chris' : '555-1111', 'Katie': '555-2222'}
value = phonebook.get('Katie')
print(value)

555-2222


In [23]:
phonebook = {'Chris' : '555-1111', 'Katie': '555-2222', 'Joanne':'555-3333'}
for key, value in phonebook.items():
    print(key, value)

Chris 555-1111
Katie 555-2222
Joanne 555-3333


In [24]:
from numpy import *
import time
def trad_version ():
    t1 = time . time ()
    X = range (10000000)
    Y = range (10000000)
    Z = []
    for i in range (len (X)):
        Z. append (X[i] + Y[i])
    return time . time () - t1

In [25]:
trad_version ()

5.02898097038269

In [26]:
def numpy_version ():
    t1 = time . time ()
    X = arange (10000000)
    Y = arange (10000000)
    Z = X + Y
    return time . time () - t1

In [27]:
numpy_version ()

0.05685091018676758

In [28]:
import numpy as np
import warnings
warnings.filterwarnings("ignore")
from IPython.display import Image

In [29]:
list1 = [10, 20, 30, 40, 50, 60]
list1

[10, 20, 30, 40, 50, 60]

In [30]:
type(list1)

list

In [31]:
arr1 = np.array(list1)
arr1

array([10, 20, 30, 40, 50, 60])

In [32]:
arr1.data

In [33]:
type(arr1)

numpy.ndarray

In [34]:
arr1.dtype

dtype('int32')

In [35]:
arr1.astype(float)

array([10., 20., 30., 40., 50., 60.])

In [36]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
np.arange(0, 100, 10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [38]:
np.arange(100, 10, -10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [39]:
arr3 = np.arange(0, 10)
arr3.shape

(10,)

In [40]:
arr3.size

10

In [41]:
arr3.nbytes

40

In [42]:
len(arr3)

10

In [43]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [44]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [45]:
np.repeat(10, 5)

array([10, 10, 10, 10, 10])

In [46]:
a = np.array([10, 20, 30])
np.repeat(a, 3)

array([10, 10, 10, 20, 20, 20, 30, 30, 30])

In [47]:
np.full(5, 10)

array([10, 10, 10, 10, 10])

In [48]:
ar1 = np.arange(1, 20)
ar1[ar1 % 2 == 1]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [49]:
ar1 = np.arange(1, 20)
ar1[ar1 % 2 == 0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [50]:
np.linspace(10, 20, 4)

array([10.        , 13.33333333, 16.66666667, 20.        ])

In [51]:
np.linspace(10, 20, 11)

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19., 20.])

In [52]:
np.random.random(4)

array([0.36081678, 0.78787173, 0.69871854, 0.296077  ])

In [53]:
np.random.randint(0, 500, 5)

array([211, 485, 436,   0, 429])

In [54]:
np.random.randint(0, 500, 10)

array([379,  53, 371, 353,  96, 190, 361, 281, 442, 382])

In [55]:
np.random.seed(123)
np.random.randint(0, 100, 10)

array([66, 92, 98, 17, 83, 57, 86, 97, 96, 47])

In [56]:
np.random.seed(123)
np.random.randint(0, 100, 10)

array([66, 92, 98, 17, 83, 57, 86, 97, 96, 47])

In [57]:
np.random.seed(101)
np.random.randint(0, 100, 10)

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [58]:
f1 = np.random.uniform(5, 10, size = (10))
f1

array([6.5348311 , 9.4680654 , 8.60771931, 5.94969477, 7.77113796,
       6.76065977, 5.90946201, 8.92800881, 9.82741611, 6.16176831])

In [59]:
np.floor(f1)

array([6., 9., 8., 5., 7., 6., 5., 8., 9., 6.])

In [60]:
np.trunc(f1)

array([6., 9., 8., 5., 7., 6., 5., 8., 9., 6.])

In [61]:
f1.astype(int)

array([6, 9, 8, 5, 7, 6, 5, 8, 9, 6])

In [62]:
b2 = np.random.randn(10)

In [63]:
b2

array([ 0.18869531, -0.75887206, -0.93323722,  0.95505651,  0.19079432,
        1.97875732,  2.60596728,  0.68350889,  0.30266545,  1.69372293])

In [64]:
arr1

array([10, 20, 30, 40, 50, 60])

In [65]:
for index, value in np.ndenumerate(arr1):
    print(index, value)

(0,) 10
(1,) 20
(2,) 30
(3,) 40
(4,) 50
(5,) 60


In [66]:
arr2 = np.arange(1, 20)
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [67]:
arr2.sum()

190

In [68]:
np.cumsum(arr2)

array([  1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,  91,
       105, 120, 136, 153, 171, 190], dtype=int32)

In [69]:
arr2.min()

1

In [70]:
arr2.max()

19

In [71]:
#mean(), var(), median()

In [72]:
np.std(arr2)

5.477225575051661

In [75]:
A = np.array([[1,2,3,0], [5,6,7,22], [10, 11, 1, 13], [14, 15, 16, 3]])
A

array([[ 1,  2,  3,  0],
       [ 5,  6,  7, 22],
       [10, 11,  1, 13],
       [14, 15, 16,  3]])

In [76]:
np.amin(A, axis = 0)

array([1, 2, 1, 0])

In [77]:
np.amin(A, axis = 1)

array([0, 5, 1, 3])

In [78]:
#mean(), var(), median(), std()

In [80]:
for index, value in np.ndenumerate(A):
    print(index, value)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 0
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 22
(2, 0) 10
(2, 1) 11
(2, 2) 1
(2, 3) 13
(3, 0) 14
(3, 1) 15
(3, 2) 16
(3, 3) 3


In [81]:
a = np.array([7,5,3,9,0,2])

In [82]:
a[0]

7

In [83]:
a[1:4]

array([5, 3, 9])

In [84]:
a[-1]

2

In [85]:
a[-3:-1]

array([9, 0])

In [86]:
ar = np.arange(1, 20)
ar

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [87]:
rep1 = np.where(ar % 2 == 0, 0, ar)
print(rep1)

[ 1  0  3  0  5  0  7  0  9  0 11  0 13  0 15  0 17  0 19]


In [88]:
ar2 = np.array([10, 20, 30, 10, 10, 20, 20])
ar2

array([10, 20, 30, 10, 10, 20, 20])

In [92]:
rep2 = np.where(ar2 == 10, 99, ar2)
print(rep2)

[99 20 30 99 99 20 20]


In [93]:
p2 = np.arange(0, 100, 10)
p2

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [94]:
np.put(p2, [0, 3, 5], [33, 55, 99])
p2

array([33, 10, 20, 55, 40, 99, 60, 70, 80, 90])